name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train models
      run: python src/train_models_mlflow.py
    
    - name: Test API
      run: |
        # Start API in background
        uvicorn src.app:app --host 0.0.0.0 --port 8000 &
        
        # Wait for API to start
        sleep 10
        
        # Run tests
        python tests/test_api.py
        
        # Kill background process
        pkill -f uvicorn

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t iris-ml-api .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8000:8000 --name test-container iris-ml-api
        sleep 30
        curl -f http://localhost:8000/ || exit 1
        docker stop test-container
        docker rm test-container
